FORMAT: 1A

# eKB APIs for LinkedData.Center
![e-artspace logo](http://www.e-artspace.com/home/images/stories/ea/ealogo-small.png)

## Overview

eKB is a set of RESTful APIs designed by [e-Artspace](http://www.e-artspace.com) to popolate and
query any knowledge base compliant with the [W3C RDF standard](http://www.w3.org/TR/rdf11-primer/) 
and with the [Knowledge Exchange Engine Service (KEES) architecture](http://www.e-artspace.com/home/project/kees).

eKB APIs are provide by all [LinkedData.Center services](LinkedData.Center).


| Resource              | GET | PUT | POST | DELETE |
|-----------------------|-----|-----|------|--------|
| /{kb}                 | X   | X   | X    | X      |
| /{kb}/sparql          | X   |     | X    |        |
| /{kb}/tasks           | X   |     | X    | X      |
| /{kb}/user/{user}/pwd |     | X   |      |        |

## The knowledge base
eKB implements a semantic system where infomation is described as a set of 
statement according with the W3C standard 
[Resource Description Framework (RDF)](http://www.w3.org/TR/rdf11-primer/).

There are two disjonined set of statemens. *TBox* and *ABox*.
Together ABox and TBox make up the whole *knowledge base*:

 - TBox statements describe a system in terms of controlled vocabularies, 
for example, a set of classes and properties such as:
**All Students are Persons** or **There are two types of Persons: Students and Teachers**.

 - ABox are TBox-compliant statements about that vocabulary. 
ABox statements describe facts about things, using vocabularies defined in Tbox such as
**John is a Person** or **Mary has blue eyes**.

In other words, TBox statements are sometimes associated with object-oriented 
classes and ABox statements associated with instances of those classes.

eKB manages both TBox and ABox statemenst.

TBox statements tend to be more permanent within a knowledge base and so they are loaded during
the knowledge base initialization (KEES booting window). 
In contrast, ABox statements are much more dynamic in nature and they are reloaded (only if changed)
during the KEES learning window. A special type of ABox statements are those that are inferred
during the KEES Reasoning windows evaluating axioms and rules contained into TBox.

eKB always traks the provenance of each statement in ABox storing all information
as linked data in a graph database (quadstore).

## Configuration
A *Knowledge Base configuration* is a collection of metadata that describe
TBox or Abox Statements.

The [KEES Ontology](http://ontology.it/kees/v1) and [VoID ontology](http://www.w3.org/TR/void/)
define the vocabularies used to express the knowlege base configuration.

TBox resources divide into *Vocabularies* and *Rules*.

Both Vocabularies and Rules statements are stored in the default graph of the graph database.
All appliable rules are executed during the KEES Reasoning windows. 

All ABox statemenst lives in named graphs.

The uri of the knowlege base configuration MUST BE *urn:kees:kb* and all knowlege base metadata 
(such is configuration info) is stored in *urn:kees* named graph.


A minimal KB configuration is like:

    <urn:kees:kb> void:subset 
            [ kees:source <http://data.example.com/file1.ttl> ]
            [ kees:source <http://data.example.com/file2.ttl> ] ;
    .
    
A more detailed KB configuration is like:

    <urn:kees:kb>
        dcterms:title "demo" ;
        dcterms:description "Contains a partial copy of dbpedia"@en ;
        dcterms:license <http://www.opendatacommons.org/odc-public-domain-dedication-and-licence/>;
        wv:norms <http://www.opendatacommons.org/norms/odc-by-sa/>;
        void:exampleResource 
            <http://dbpedia.org/resource/Berlin> , 
            <http://dbpedia.org/resource/Physics> ,
            <http://dbpedia.org/resource/Ludwig_van_Beethoven> ;

        #TBox
        void:vocabulary <http://purl.org/goodrelations/v1.owl>;
        kees:rule
            [
                a kees:Rule
                kees:ruleContent   """
                    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
                    PREFIX gr: <http://purl.org/goodrelations/v1#>
                    PREFIX :<urn:test:>
                    IF {
                        ?offering gr:hasPriceSpecification ?ps .
                        ?ps gr:hasCurrencyValue ?price .
                        FILTER (?price >= 200.00).
                    }
                    THEN {
                        ?offering a :ExpensiveProduct .
                    }
               """.
            ]
        ;
           
        # ABox
        void:subset 
            [
                a kees:ABoxGraph;
                kees:source <http://data.example.com/file1.ttl> ;
                kees:accrualPeriodicity kees:montly ;
                kees:accrualPolicy kees:simpleLearning ;
            ],
            [ kees:source <http://data.example.com/file2.ttl> ] ;
    .

    
The knowledge base configuration is always initialized with:

    <urn:kees:kb> a kees:KnowledgeBase ;
        foaf:homepage <> ;
        void:feature 
            <http://www.w3.org/ns/formats/RDF_XML> ,
            <http://www.w3.org/ns/formats/Turtle> ,
            <http://www.w3.org/ns/formats/N-Triples> ;
        void:sparqlEndpoint <sparql>;
    .

## Autentication

To access eKB APIs you always need to provide your LinkedData.Center credentials using
[http basic authentication](http://en.wikipedia.org/wiki/Basic_access_authentication):

+ Authorization ... [Base64](http://en.wikipedia.org/wiki/Base64) encoded string literal in form _"username:password"_ preceeded by authorization method and its space.


## Content negotiation
All eKB APIs supports [http content negotiation](http://en.wikipedia.org/wiki/Content_negotiation) 
for state representation rendering.
Following MIME types are supported in the Accept header: text/html, application/rdf+xml, text/turtle.
Support to other mimetype  like application/x-turtle, text/x-nquads OR application/ld+json 
is experimental.

You can use *_output=mimetype* parameter in any URL to override http content negotiation 
and forcing your preferred resource representation. 

## Server Responses

Following table sumarize typical http status code returned by APIS

| Code | Description                                                                                     | 
|------|-------------------------------------------------------------------------------------------------|
| 200  | Request was successful                                                                          |
| 201  | Request was successful and the resource was created                                             |
| 202  | Request was successfully queued                                                                 |
| 400  | Indicates parse errors or that the transaction identifier specified for an operation is invalid or does not correspond to a known transaction. |
| 401  | Request is unauthorized.                                                                        |
| 403  | User attempting to perform the operation does not exist, their username or password is invalid, or they do not have the proper credentials to perform the action. |
| 404  | A resource involved in the operation, such as a user or transaction, does not exist.            |
| 405  | Requested method is not supported.                                                              |
| 409  | A conflict for some database operations; for example, creating a database that already exists.  |
| 500  | An unspecified failure in the server.                                                           |
| 503  | The eKB serve is learnig new resources or is reasoning. Sparql interface is temporary disabled. |

Error representation is based on [ietf specs](http://tools.ietf.org/html/draft-nottingham-http-problem-07).
Here is an example of a 404 error in json representation:

       HTTP/1.1 404 Not found
       Content-Type: application/problem+json
       Content-Language: en

        {
            problemType: "http://dbpedia.org/resource/Category:HTTP_status_codes"
            title: "Job not found"
            detail: "Job report 5441392469671 not found."
            problemInstance: "http://dbpedia.org/resource/HTTP_404"
            httpStatus: 404
        }




## Knowledge base configuration API [/{kb}]

+ Parameters
    + kb (required, string, `demo`) ... `id` of the Knowlege base  

### Get configuration [GET]

Returns the current knowledge base config.

+ Request (text/turtle)

    + Headers
    
            Accept: text/turtle
            
+ Response 200


    + Body
    
            @prefix void: <http://rdfs.org/ns/void#> .
            @prefix foaf: <http://xmlns.com/foaf/0.1/> ..
            @prefix kees: <http://ontology.it/kees/v1#> .
            
            # created by boot windows
            <urn:kees:kb> a kees:KnowledgeBase ;
                foaf:homepage <> ;
                void:feature 
                    <http://www.w3.org/ns/formats/RDF_XML> ,
                    <http://www.w3.org/ns/formats/Turtle> ,
                    <http://www.w3.org/ns/formats/N-Triples> ;
                void:sparqlEndpoint <sparql>;
            .



### Override current configuration [PUT]

Substitute the knowledge base configuration with the request bosy content.

+ Request (text/turtle)
            
    + Body

            [] a kees:KnowledgeBase ;
                void:subset 
                    [ kees:source <http://data.example.com/file1.ttl> ]
                    [ kees:source <http://data.example.com/file2.ttl> ] ;
            .    
            
+ Response 200

    + Body
    
            Knowledge base configuration updated.



### Upload a new configuration [POST]

This API allows you to upload a RDF file containing a knowledge base configuration.
The file contents replace current configuration.

+ Parameters
    + kb (required, string, `demo`) ... `id` of the Knowlege base  
            
+ Response 200

    + Body
    
            New configuration uploaded.
            
### Empty the configuration [DELETE]

This API delete knowledge base configuration. It is equivalent to a call to
*sparql?query=DROP SILENT ALL* 

+ Response 200

    + Body
    
            true
            

## SPARQL API [/{kb}/sparql{?guard,query}]

**Protection from inconsistent data**

The knowledge base may be in a state temporarily inconsistent during the phases 
of acquisition of new data (learning window) or during the steps of the inference computation (reasoning window).
During these temporary windows, the result of the query to the knowledge base may be incorrect.

The endpoint is protected by a guard that prevents query during learning and reasoning windows. 
In these cases, any access to the endpoint receives a 503 error (Service Unavailable). 
The http header *Retry-After* contains an estimate of the time (in seconds) that you should wait before attempting a new access.

The endpoint guard can be disabled using the optional paramether guard=disabled.


+ Parameters
    + kb (required, string, `demo`) ... `id` of the Knowlege base  
    + query (optional, string, `SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D`) ... url encoded sparql query.
    + guard (optional, string, `enable`) ... block access during learning.
    
        | Value        | Meaning                                                |
        | ------------ |:------------------------------------------------------:|
        | enable       | block endpoint during learning and reasoning (default) |
        | disable      | always allow endpoint access                           |

        + Values
            + `enable`
            + `disable`


+ Model (application/sparql-results+xml)

    See [SPARQL Query Results XML Format](http://www.w3.org/TR/rdf-sparql-XMLres/) for more info.
            
    + Body

            <?xml version='1.0' encoding='UTF-8'?>
            <sparql xmlns='http://www.w3.org/2005/sparql-results#'>
                <head>
                    <variable name='s'/>
                    <variable name='p'/>
                    <variable name='o'/>
                </head>
                <results>
                </results>
            </sparql> 

### SPARQL query via get [GET]
This end point implements [SPARQL 1.1 protocol](http://www.w3.org/TR/sparql11-protocol/) 
for [query](http://www.w3.org/TR/sparql11-query/) and [update](http://www.w3.org/TR/sparql11-update/) language specifications.
It also supports [Service Description](http://www.w3.org/TR/sparql11-service-description/) specification.

SPARQL query APIs support [http content negotiation](http://en.wikipedia.org/wiki/Content_negotiation) for state representation rendering.

All HTTP requests that are mutative (add or remove) must include a valid Content-Type header set to the MIME type of the request body,
 where “valid” is a valid MIME type for N-Triples(text/plain), Turtle (application/x-turtle or text/turtle), NQuads (text/x-nquads), JSON-LD(application/ld+json), or RDF/XML (application/rdf+xml).
 
Depending from SPARQL query, following MIME types are recognized in the Accept header:

| Query type | Supported MIMETYPE in Accept header                                                                |
|------------|----------------------------------------------------------------------------------------------------|
| SELECT     | application/sparql-results+xml OR application/sparql-results+json                                  |
| ASK        | text/boolean                                                                                       |
| CONSTRUCT  | application/rdf+xml OR text/turtle OR application/x-turtle OR text/x-nquads OR application/ld+json |


If no query parameter is supplied it returns 
[end-point service Description](http://www.w3.org/TR/sparql11-service-description/) in one of available RDF serialization.


+ Request (application/x-www-form-urlencoded)

    + Headers
    
            Accept: application/sparql-results+xml
            
+ Response 200

    [SPARQL API][]



### SPARQL query via post [POST]
Post action can be used for queries whose length exceeds the maximum allowed number of characters in a URI.
The body of the request should be same form-encoded parameters of the GET variant.

+ Request (application/x-www-form-urlencoded)

    + Headers
    
            Accept: application/sparql-results+xml

    + Body

            query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D
            
+ Response 200

    [SPARQL API][]



## Tasks API [/{kb}/tasks{?status,type}]

Populate the knowledge base drivinig a KEES Booting, Learning and Reasoning windows. 

Tasks are executed asyncronusly as soon as there  are enough resources available in the system.

Each task is provided with an unique id in the knowledge base. 
The task state can be inspected before, after and during execution.
Tasks information is stored in <urn:kees> named graph.

+ Authorization ... [Base64](http://en.wikipedia.org/wiki/Base64) encoded string literal in form _"username:password"_ preceeded by authorization method and its space.

+ Parameters
    + kb (required, string, `demo`) ... `id` of the Knowlege base  


### List task [GET]
Lists tasks (pending, running and complete). By default, completed tasks are retained 
for one day before to be purged.

+ Parameters
    + status (optional, string, `running`) ... show only task in a defined status.
    
        + Values
            + `all`
            + `pending`
            + `running`
            + `complete`
            + `lastcomplete`
            + `tobepurged`


    + type (optional, string, `all`) ... block access during learning.

        + Values
            + `all`
            + `booting`
            + `learning`
            + `reasoning`


+ Request

    + Headers
        
            Accept: text/turtle
 
+ Response 200


    + Headers
        
            Content-type: text/turtle
            
    + Body
    
            <urn:kees:task:xxx> a kees:LearningTask;
                dcterms:identifier "xxx" ;
                dcterms:dateSubmitted "......"^xsd:datetime ;
            .
            <urn:kees:task:yyy> a kees:ReasoningTask;
                dcterms:identifier "yyy" ;
                dcterms:dateSubmitted "......"^xsd:datetime ;
            .


### Start a KEES cycle [POST]
Ask for a new kees cicle to be executed as soon as possible.

Accepts following x-www-form-urlencoded vars:

| var       | default| type              | description                         |
|-----------|------- |-------------------|-------------------------------------|
| booting   | false  | 'true' or 'false' | Request booting window processing   |
| learning  | true   | 'true' or 'false' | Request learning window processing  |
| reasoning | true   | 'true' or 'false' | Request reasoning window processing |

+ Request (application/x-www-form-urlencoded)

    + Body

            booting=false&learning=true&reasoning=true
        
+ Response 200 (application/json)

    + Headers
        
            Link: <tasks?status=pending>; rel="pending"
            
    + Body
    
            Tasks submitted

### Delete pending tasks [DELETE]
Deletes all pending tasks.

            
+ Response 200

        All pending tasks deleted



## Change authentication password [/{kb}/user/{user}/pwd]
Changes the password of the knowledge admin user. 


+ Authorization ... [Base64](http://en.wikipedia.org/wiki/Base64) encoded string literal in form _"username:password"_ preceeded by authorization method and its space.

+ Parameters
    + kb (required, string, `gate1`) ... `id` of the user (same as Knowlege base kb) 
    + user (required, string, `admin`) ... `id` of the user (same as Knowlege base kb)

### Change user password [PUT]
+ Request

    + Body
    
            newpassword
            
+ Response 200

    + Body
    
            Password changed.

